[package]
name = "velvet-lang"
version = "0.1.0"
edition = "2021"
description = "Velvet Programming Language Compiler"
license = "MIT"

[dependencies]
# Rust dependencies for CLI and compiler core
clap = { version = "4.5", features = ["derive"] } # CLI argument parsing (Cargo-like)
colored = "2.1" # Colored terminal output for errors
serde = { version = "1.0", features = ["derive"] } # Serialization for config/AST
serde_json = "1.0" # JSON handling for internal data
anyhow = "1.0" # Error handling

[build-dependencies]
# For invoking Python/Zig during build
fs_extra = "1.3" # File system utilities

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1
debug = true
